### ISSUE TITLE
Automatic error report for Gauzy Desktop Timer App 0.409.27

### ISSUE THREAD

**Issue by ryannjayherrera** [ever-co/ever-gauzy-desktop-timer#41]
### Description 🐊
 ```
Error: ERR_FAILED (-2) loading 'https://accounts.google.com/o/oauth2/v2/auth?response_type=code&redirect_uri=http%3A%2F%2F127.0.0.1%3A3000%2Fapi%2Fauth%2Fundefined%2Fapi%2Fauth%2Fgoogle%2Fcallback&scope=email%20profile&client_id=disabled'
    at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)
    at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:161:8022)
    at EventEmitter.emit (node:events:539:35)
    at EventEmitter.emit (node:domain:475:12)
```

### To Reproduce 🧵
Response... 

### Screenshots 📸
Response... 

### Additional Information ⚓️
Response...  

### Configuration 🛠 
App Version ⛓: **0.409.27**
Platform 🖥: **win32 x64**
Release 📦: **10.0.22621**

**Comment by evereq** [comment]
@ryannjayherrera at the moment, Google Auth is not configured yet in our live env, please use password auth. Thank you!

**Comment by evereq** [comment]
Related: https://github.com/ever-co/ever-gauzy/issues/42

**Comment by ryannjayherrera** [comment]
Got it, thank you.
