### ISSUE TITLE
Automatic error report for Gauzy Desktop Timer App 0.412.13

### ISSUE THREAD

**Issue by jpsdm** [ever-co/ever-gauzy-desktop-timer#42]
### Description 🐊
 ```
Error: ERR_FAILED (-2) loading 'https://accounts.google.com/o/oauth2/v2/auth?response_type=code&redirect_uri=https%3A%2F%2Fapi.gauzy.co%2Fapi%2Fauth%2Fgoogle%2Fcallback&scope=email%20profile&client_id=disabled'
    at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)
    at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:161:8022)
    at EventEmitter.emit (node:events:539:35)
    at EventEmitter.emit (node:domain:475:12)
```

### To Reproduce 🧵
Response... 

### Screenshots 📸
Response... 

### Additional Information ⚓️
Response...  

### Configuration 🛠 
App Version ⛓: **0.412.13**
Platform 🖥: **win32 x64**
Release 📦: **10.0.22631**

**Comment by evereq** [comment]
@jpsoarxs at the moment, Google Auth is not configured yet in our live env, please use password auth. Thank you! 
Related: https://github.com/ever-co/ever-gauzy/issues/42
